### ISSUE TITLE
hello，nomodule  named 'torch_geometric.data.storage'

### ISSUE THREAD

**Issue by yuwanting828** [leftthomas/DGCNN#2]
![image](https://user-images.githubusercontent.com/88610502/168202630-b8893655-aa82-4fbb-bb38-d4b35f2f166c.png)

**Comment by leftthomas** [comment]
@yuwanting828 you should read `readme`.

**Comment by yuwanting828** [comment]
Thank you. I configured the environment according to readme, did not understand the error, and did not search for it on the internet.

**Comment by leftthomas** [comment]
@yuwanting828  you should go to `torch_geometric` website to find the solution.
